### ISSUE TITLE
The project main wont repeat itself.

### ISSUE THREAD

**Issue by Sammylandler** [Sammylandler/statistics#2]
The application won't repeat itself. The goal is for it to repeat itself until you tell it to stop by pressing the 5 key.
![terminal](https://cloud.githubusercontent.com/assets/19352597/25658921/e58061fa-2fca-11e7-888a-6462bb4f303c.png)

**Comment by Sammylandler** [comment]
It decides to "return 0;" before I want it to.

**Comment by macetw** [comment]
Then you need a do while loop within main() and have most of your code within that loop.

**Comment by Sammylandler** [comment]
I fixed the problem with a boolean and a do while loop.
